# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 06:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'verbose_name': ('categoria',),
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200)),
                ('titulo', models.CharField(db_index=True, max_length=50)),
                ('plataforma', models.CharField(choices=[('ps3', 'Playstation 3'), ('xbox', 'Xbox'), ('xboxone', 'Xbox One'), ('wii', 'Nintendo Wii'), ('xbox360', 'Xbox 360'), ('ps4', 'Playstation 4'), ('ps2', 'Playstation 2')], db_index=True, max_length=50)),
                ('preciorenta', models.FloatField(blank=True, null=True)),
                ('deposito', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='media')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='juego.Categoria')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
