# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'categorias',
                'verbose_name': ('categoria',),
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=200)),
                ('plataforma', models.CharField(choices=[('ps2', 'Playstation 2'), ('wii', 'Nintendo Wii'), ('xbox', 'Xbox'), ('ps3', 'Playstation 3'), ('xboxone', 'Xbox One'), ('ps4', 'Playstation 4'), ('xbox360', 'Xbox 360')], db_index=True, max_length=50)),
                ('fecha_alta', models.DateTimeField(auto_now=True)),
                ('precio_renta', models.FloatField(blank=True, null=True)),
                ('deposito', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(choices=[('MOR', 'Morelos'), ('JAL', 'Jalisco'), ('SLP', 'San Luis Potosí'), ('AGU', 'Aguascalientes'), ('NAY', 'Nayarit'), ('COL', 'Colima'), ('DUR', 'Durango'), ('PUE', 'Puebla'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('GUA', 'Guanajuato'), ('TAM', 'Tamaulipas'), ('TLA', 'Tlaxcala'), ('CDMX', 'Ciudad de Mexico'), ('GRO', 'Guerrero'), ('MIC', 'Michoacán'), ('QUE', 'Querétaro'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas'), ('CHP', 'Chiapas'), ('OAX', 'Oaxaca'), ('CHH', 'Chihuahua'), ('HID', 'Hidalgo'), ('NLE', 'Nuevo León'), ('MEX', 'Estado de México'), ('ROO', 'Quintana Roo'), ('SIN', 'Sinaloa'), ('TAB', 'Tabasco'), ('CAM', 'Campeche'), ('COA', 'Coahuila'), ('SON', 'Sonora')], max_length=100)),
                ('imagen', models.ImageField(upload_to='media')),
                ('prefijo', models.CharField(max_length=3)),
                ('telefono', models.CharField(max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='juego.Categoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
