# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='plataforma',
            field=models.CharField(choices=[('xbox', 'Xbox'), ('ps3', 'Playstation 3'), ('wii', 'Nintendo Wii'), ('ps4', 'Playstation 4'), ('xboxone', 'Xbox One'), ('xbox360', 'Xbox 360'), ('ps2', 'Playstation 2')], db_index=True, max_length=50),
        ),
    ]
