# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_auto_20160402_0205'),
        ('juego', '0003_merge'),
    ]

    operations = [
    ]
