# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0006_auto_20160408_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='juego.Categoria'),
        ),
    ]
