# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0007_auto_20160408_0211'),
        ('juego', '0005_auto_20160406_2208'),
    ]

    operations = [
    ]
