# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0008_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'categorias',
                'verbose_name': ('categoria',),
            },
        ),
        migrations.AlterField(
            model_name='juego',
            name='categoria',
            field=models.CharField(blank=True, choices=[('accion', 'Accion'), ('aventura', 'Aventura'), ('carreras', 'Carreras'), ('clasicos', 'Clasicos'), ('terror', 'Terror')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='fecha_alta',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('ps2', 'Playstation 2'), ('ps3', 'Playstation 3'), ('ps4', 'Playstation 4'), ('wii', 'Nintendo Wii'), ('xbox', 'Xbox'), ('xbox360', 'Xbox 360'), ('xboxone', 'Xbox One')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('AGU', 'Aguascalientes'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CDMX', 'Ciudad de Mexico'), ('CHH', 'Chihuahua'), ('CHP', 'Chiapas'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DUR', 'Durango'), ('GRO', 'Guerrero'), ('GUA', 'Guanajuato'), ('HID', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MIC', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QUE', 'Querétaro'), ('ROO', 'Quintana Roo'), ('SIN', 'Sinaloa'), ('SLP', 'San Luis Potosí'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLA', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=100, null=True),
        ),
    ]
